//SEGMENTO DE --- AUTENTICAR  ---
export const CERRAR_SESION       = 'CERRAR_SESION';
export const LOGIN_EXITOSO       = 'LOGIN_EXITOSO';
export const LOGIN_ERROR         = 'LOGIN_ERROR';
export const LIMPIAR_MENSAJE     = 'LIMPIAR_MENSAJE';



//SEGMENTO DE --- USUARIO  ---
export const REGISTRO_USUARIO_EXITOSO    = 'REGISTRO_USUARIO_EXITOSO';
export const REGISTRO_USUARIO_ERROR      = 'REGISTRO_USUARIO_ERROR';

export const OLVIDO_CLAVE_EXITOSO  = 'OLVIDO_CLAVE_EXITOSO';
export const OLVIDO_CLAVE_ERROR    = 'OLVIDO_CLAVE_ERROR';

export const CAMBIO_CLAVE_EXITOSO  = 'CAMBIO_CLAVE_EXITOSO';
export const CAMBIO_CLAVE_ERROR    = 'CAMBIO_CLAVE_ERROR';


//SEGMENTO DE --- CATEGORIA ---

export const LISTAR_CATEGORIA          = 'LISTAR_CATEGORIA';
export const LISTAR_CATEGORIA_ERROR    = 'LISTAR_CATEGORIA_ERROR';

export const CREAR_CATEGORIA_ERROR     = 'CREAR_CATEGORIA_ERROR';
export const CREAR_CATEGORIA_EXITO     = 'CREAR_CATEGORIA_EXITO';

export const ELIMINAR_CATEGORIA_ERROR     = 'ELIMINAR_CATEGORIA_ERROR';
export const ELIMINAR_CATEGORIA_EXITO     = 'ELIMINAR_CATEGORIA_EXITO';

export const EDITAR_CATEGORIA_ERROR     = 'EDITAR_CATEGORIA_ERROR';
export const EDITAR_CATEGORIA_EXITO     = 'EDITAR_CATEGORIA_EXITO';


//SEGMENTO DE --- SUBCATEGORIA ---

export const LISTAR_SUBCATEGORIA          = 'LISTAR_SUBCATEGORIA';
export const LISTAR_SUBCATEGORIA_ERROR    = 'LISTAR_SUBCATEGORIA_ERROR';

export const MUTAR_SUBCATEGORIA_ERROR     = 'MUTAR_SUBCATEGORIA_ERROR';
export const MUTAR_SUBCATEGORIA_EXITO     = 'MUTAR_SUBCATEGORIA_EXITO';

export const ELIMINAR_SUBCATEGORIA_ERROR     = 'ELIMINAR_SUBCATEGORIA_ERROR';
export const ELIMINAR_SUBCATEGORIA_EXITO     = 'ELIMINAR_SUBCATEGORIA_EXITO';


//SEGMENTO DE --- RECURRENTE ---

export const LISTAR_RECURRENTE          = 'LISTAR_RECURRENTE';
export const LISTAR_RECURRENTE_ERROR    = 'LISTAR_RECURRENTE_ERROR';

export const MUTAR_RECURRENTE_ERROR     = 'MUTAR_RECURRENTE_ERROR';
export const MUTAR_RECURRENTE_EXITO     = 'MUTAR_RECURRENTE_EXITO';

export const ELIMINAR_RECURRENTE_ERROR     = 'ELIMINAR_RECURRENTE_ERROR';
export const ELIMINAR_RECURRENTE_EXITO     = 'ELIMINAR_RECURRENTE_EXITO';


//SEGMENTO DE --- ACTO  ---

export const LISTAR_ACTO          = 'LISTAR_ACTO';
export const LISTAR_ACTO_ERROR    = 'LISTAR_ACTO_ERROR';

export const MUTAR_ACTO_ERROR     = 'MUTAR_ACTO_ERROR';
export const MUTAR_ACTO_EXITO     = 'MUTAR_ACTO_EXITO';

export const ELIMINAR_ACTO_ERROR     = 'ELIMINAR_ACTO_ERROR';
export const ELIMINAR_ACTO_EXITO     = 'ELIMINAR_ACTO_EXITO';

//SEGMENTO DE --- ACTO  SEMANA ---
export const LISTAR_ACTO_SEMANA          = 'LISTAR_ACTO_SEMANA';
export const LISTAR_ACTO_ERROR_SEMANA    = 'LISTAR_ACTO_ERROR_SEMANA';


